# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import game_pb2 as game__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in game_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGame = channel.unary_unary(
                '/universal_game_engine.GameService/CreateGame',
                request_serializer=game__pb2.CreateGameRequest.SerializeToString,
                response_deserializer=game__pb2.CreateGameResponse.FromString,
                _registered_method=True)
        self.DispatchAction = channel.unary_unary(
                '/universal_game_engine.GameService/DispatchAction',
                request_serializer=game__pb2.DispatchActionRequest.SerializeToString,
                response_deserializer=game__pb2.CommonResponse.FromString,
                _registered_method=True)
        self.SendChat = channel.unary_unary(
                '/universal_game_engine.GameService/SendChat',
                request_serializer=game__pb2.ChatMessage.SerializeToString,
                response_deserializer=game__pb2.CommonResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/universal_game_engine.GameService/StreamEvents',
                request_serializer=game__pb2.JoinGameRequest.SerializeToString,
                response_deserializer=game__pb2.GameEvent.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/universal_game_engine.GameService/Step',
                request_serializer=game__pb2.StepRequest.SerializeToString,
                response_deserializer=game__pb2.StepResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/universal_game_engine.GameService/Reset',
                request_serializer=game__pb2.ResetGameRequest.SerializeToString,
                response_deserializer=game__pb2.ResetGameResponse.FromString,
                _registered_method=True)
        self.Simulate = channel.unary_unary(
                '/universal_game_engine.GameService/Simulate',
                request_serializer=game__pb2.SimulateRequest.SerializeToString,
                response_deserializer=game__pb2.SimulateResponse.FromString,
                _registered_method=True)
        self.BatchSimulate = channel.unary_unary(
                '/universal_game_engine.GameService/BatchSimulate',
                request_serializer=game__pb2.BatchSimulateRequest.SerializeToString,
                response_deserializer=game__pb2.BatchSimulateResponse.FromString,
                _registered_method=True)
        self.WaitForTurn = channel.unary_stream(
                '/universal_game_engine.GameService/WaitForTurn',
                request_serializer=game__pb2.WaitForTurnRequest.SerializeToString,
                response_deserializer=game__pb2.WaitForTurnResponse.FromString,
                _registered_method=True)
        self.SubmitTurn = channel.unary_unary(
                '/universal_game_engine.GameService/SubmitTurn',
                request_serializer=game__pb2.SubmitTurnRequest.SerializeToString,
                response_deserializer=game__pb2.CommonResponse.FromString,
                _registered_method=True)


class GameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateGame(self, request, context):
        """単発のRPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DispatchAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """サーバーからのプッシュ（gRPC-webではサーバーサイドストリーミングを常用）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """AI学習ループ専用のエンドポイント
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Simulate(self, request, context):
        """木探索用のステートレスなシミュレーション
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchSimulate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitForTurn(self, request, context):
        """AIプレイ用のエンドポイント
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGame,
                    request_deserializer=game__pb2.CreateGameRequest.FromString,
                    response_serializer=game__pb2.CreateGameResponse.SerializeToString,
            ),
            'DispatchAction': grpc.unary_unary_rpc_method_handler(
                    servicer.DispatchAction,
                    request_deserializer=game__pb2.DispatchActionRequest.FromString,
                    response_serializer=game__pb2.CommonResponse.SerializeToString,
            ),
            'SendChat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendChat,
                    request_deserializer=game__pb2.ChatMessage.FromString,
                    response_serializer=game__pb2.CommonResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=game__pb2.JoinGameRequest.FromString,
                    response_serializer=game__pb2.GameEvent.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=game__pb2.StepRequest.FromString,
                    response_serializer=game__pb2.StepResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=game__pb2.ResetGameRequest.FromString,
                    response_serializer=game__pb2.ResetGameResponse.SerializeToString,
            ),
            'Simulate': grpc.unary_unary_rpc_method_handler(
                    servicer.Simulate,
                    request_deserializer=game__pb2.SimulateRequest.FromString,
                    response_serializer=game__pb2.SimulateResponse.SerializeToString,
            ),
            'BatchSimulate': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchSimulate,
                    request_deserializer=game__pb2.BatchSimulateRequest.FromString,
                    response_serializer=game__pb2.BatchSimulateResponse.SerializeToString,
            ),
            'WaitForTurn': grpc.unary_stream_rpc_method_handler(
                    servicer.WaitForTurn,
                    request_deserializer=game__pb2.WaitForTurnRequest.FromString,
                    response_serializer=game__pb2.WaitForTurnResponse.SerializeToString,
            ),
            'SubmitTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTurn,
                    request_deserializer=game__pb2.SubmitTurnRequest.FromString,
                    response_serializer=game__pb2.CommonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'universal_game_engine.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('universal_game_engine.GameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/universal_game_engine.GameService/CreateGame',
            game__pb2.CreateGameRequest.SerializeToString,
            game__pb2.CreateGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DispatchAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/universal_game_engine.GameService/DispatchAction',
            game__pb2.DispatchActionRequest.SerializeToString,
            game__pb2.CommonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/universal_game_engine.GameService/SendChat',
            game__pb2.ChatMessage.SerializeToString,
            game__pb2.CommonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/universal_game_engine.GameService/StreamEvents',
            game__pb2.JoinGameRequest.SerializeToString,
            game__pb2.GameEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/universal_game_engine.GameService/Step',
            game__pb2.StepRequest.SerializeToString,
            game__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/universal_game_engine.GameService/Reset',
            game__pb2.ResetGameRequest.SerializeToString,
            game__pb2.ResetGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Simulate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/universal_game_engine.GameService/Simulate',
            game__pb2.SimulateRequest.SerializeToString,
            game__pb2.SimulateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchSimulate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/universal_game_engine.GameService/BatchSimulate',
            game__pb2.BatchSimulateRequest.SerializeToString,
            game__pb2.BatchSimulateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitForTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/universal_game_engine.GameService/WaitForTurn',
            game__pb2.WaitForTurnRequest.SerializeToString,
            game__pb2.WaitForTurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/universal_game_engine.GameService/SubmitTurn',
            game__pb2.SubmitTurnRequest.SerializeToString,
            game__pb2.CommonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
