export const availableGames = [
  {
    type: "tictactoe",
    name: "Tic Tac Toe",
    description: "古典的な三目並べ。",
    emoji: "⭕",
    minPlayers: 2,
    maxPlayers: 2,
    category: "Board Games",
    rules: "3x3のマス目に○と×を交互に書き、3つ並べたほうが勝ちというシンプルなゲーム。",
  },
  {
    type: "othello",
    name: "Othello",
    description: "3D対応の本格オセロ（リバーシ）。",
    emoji: "⚫",
    minPlayers: 2,
    maxPlayers: 2,
    category: "Board Games",
    rules: "相手の石を挟んで自分の色に変える、伝統的なボードゲームです。最後に石が多いほうが勝ち。",
  },
  {
    type: "othello_3d",
    name: "3D Othello",
    description: "3D立体オセロ。26方向に挟める！",
    emoji: "🟦",
    minPlayers: 2,
    maxPlayers: 2,
    category: "Board Games",
    rules:
      "石を置いて、上下左右、斜めに加えて、高さ（Z軸）方向も含む26方向に相手の石を挟んで自分の色に変えます。",
  },
  {
    type: "high_low",
    name: "High-Low Card",
    description: "引いたカードの強さで競うカードゲーム。",
    emoji: "🃏",
    minPlayers: 1,
    maxPlayers: 2,
    category: "Card Games",
    rules: "次に引くカードが現在のカードより「高い」か「低い」かを予想します。",
  },
  {
    type: "shogi",
    name: "将棋 (Shogi)",
    description: "日本の伝統的なボードゲーム。3D。",
    emoji: "☖",
    minPlayers: 2,
    maxPlayers: 2,
    category: "Board Games",
    rules: "取った駒を自駒として使えるのが特徴です。相手の玉将を詰ませれば勝利。",
  },
  {
    type: "shogi_3d",
    name: "Shogi 3D",
    description: "3D化した将棋。高級感のある駒と盤面。",
    emoji: "☖",
    minPlayers: 2,
    maxPlayers: 2,
    category: "Board Games",
    rules: "日本の伝統的なボードゲーム「将棋」を3Dで楽しめます。",
  },
  {
    type: "chess",
    name: "Chess (2D)",
    description: "世界的に人気の伝統的なチェス。",
    emoji: "♟️",
    minPlayers: 2,
    maxPlayers: 2,
    category: "Board Games",
    rules:
      "キング、クイーン、ルーク、ビショップ、ナイト、ポーンを動かして、相手のキングをチェックメイトします。",
  },
  {
    type: "chess_3d",
    name: "Chess 3D",
    description: "3D化されたチェス。駒のモデルをロード可能。",
    emoji: "♔",
    minPlayers: 2,
    maxPlayers: 2,
    category: "Board Games",
    rules:
      "キング、クイーン、ルーク、ビショップ、ナイト、ポーンを動かして、相手のキングをチェックメイトします。3Dモデルの駒を使用します。",
  },
  {
    type: "daifugo",
    name: "Daifugo",
    description: "トランプの定番、大富豪。",
    emoji: "🎴",
    minPlayers: 2,
    maxPlayers: 6,
    category: "Card Games",
    rules:
      "手札を早く出し切り、大富豪を目指すトランプゲームです。革命や階段などの独自ルールもあります。",
  },
  {
    type: "texas_holdem",
    name: "Texas Hold'em",
    description: "本格ポーカー、テキサスホールデム。",
    emoji: "🎰",
    minPlayers: 2,
    maxPlayers: 8,
    category: "Card Games",
    rules: "2枚の手札と5枚の共通カードを組み合わせて最強の役を作ります。",
  },
  {
    type: "go",
    name: "Go (囲碁)",
    description: "伝統的な囲碁ゲーム。",
    emoji: "⚪",
    minPlayers: 2,
    maxPlayers: 2,
    category: "Board Games",
    rules: "石で盤面の囲いを広げ、陣地の広さを競います。",
  },
  {
    type: "rubiks_cube",
    name: "Rubik's Cube",
    description: "1人用ルービックキューブ。3D。",
    emoji: "🟥",
    minPlayers: 1,
    maxPlayers: 1,
    category: "Puzzles",
    rules: "6つの面の各色を揃える立体パズルです。",
  },
  {
    type: "sudoku",
    name: "数独 (Sudoku)",
    description: "9×9マスに数字を配置する定番パズル。",
    emoji: "🔢",
    minPlayers: 1,
    maxPlayers: 1,
    category: "Puzzles",
    rules: "9x9のマス目に1から9の数字を、各行・各列・3x3ブロックで重複しないように配置します。",
  },
  {
    type: "equilibrium",
    name: "Equilibrium",
    description: "AIが考案した、魂を削り合う究極の心理戦ボードゲーム。",
    emoji: "⚖️",
    minPlayers: 3,
    maxPlayers: 6,
    category: "Special",
    rules: "AIによって設計された戦略的なボードゲーム。相手の心理を読み、均衡を崩します。",
  },
  {
    type: "uno",
    name: "UNO",
    description: "UNO。",
    emoji: "🃏",
    minPlayers: 2,
    maxPlayers: 10,
    category: "Card Games",
    rules: "同じ色か同じ数字のカードを出していき、最初に手札がなくなった人の勝ちです。",
  },
  {
    type: "mancala",
    name: "Mancala",
    description: "最古のボードゲームの一つ。石をまいて自分のストアに集めよう。",
    emoji: "🏺",
    minPlayers: 2,
    maxPlayers: 2,
    category: "Board Games",
    rules:
      "自分の陣地の穴から石を選んで、時計回りに一つずつ置いていきます。最後に自分のストアに多くの石がある人の勝ちです。",
  },
  {
    type: "mahjong",
    name: "Mahjong (麻雀)",
    description: "本格的な四人麻雀。",
    emoji: "🀄",
    minPlayers: 4,
    maxPlayers: 4,
    category: "Board Games",
    rules: "4人で牌を引き合い、特定の役を揃える伝統的なゲームです。",
  },
  {
    type: "wordle",
    name: "Wordle",
    description: "5文字の単語を当てるパズルゲーム。",
    emoji: "🟩",
    minPlayers: 1,
    maxPlayers: 1,
    category: "Puzzles",
    rules:
      "6回以内に5文字の英単語を当ててください。入力後、文字の位置が合っていれば緑、文字は含まれるが位置が違えば黄色、含まれていなければ灰色で表示されます。",
  },
  {
    type: "speed",
    name: "Speed",
    description: "トランプの「スピード」。場札と±1の数字のカードを素早く出せ！",
    emoji: "⚡",
    minPlayers: 2,
    maxPlayers: 2,
    category: "Card Games",
    rules:
      "台札と数字が1つ違い（A-2-3...K-A）のカードを、手札から場に出します。手札は山札から自動で5枚まで補充されます。先に全て出し切った方の勝ちです。詰まったら「めくる」ボタンで脇の札を台札に移動します。",
  },
  {
    type: "minesweeper",
    name: "Minesweeper",
    description: "数字をヒントに地雷を避ける名作パズル。",
    emoji: "💣",
    minPlayers: 1,
    maxPlayers: 1,
    category: "Puzzles",
    rules:
      "マスの数字は周囲8マスの地雷の数を示します。これをヒントに地雷がないマスをすべて開ければ勝ちです。",
  },
  {
    type: "hakoiri_musume",
    name: "箱入り娘 (Hakoiri Musume)",
    description: "古典的なスライディングパズル。",
    emoji: "👧",
    minPlayers: 1,
    maxPlayers: 1,
    category: "Puzzles",
    rules:
      "4x5の盤面で駒をスライドさせ、2x2の「娘」の駒を中央下部の出口まで移動させるパズルゲームです。",
  },
  {
    type: "tower_of_hanoi",
    name: "Tower of Hanoi",
    description: "古典的な数学パズル「ハノイの塔」。",
    emoji: "🗼",
    minPlayers: 1,
    maxPlayers: 1,
    category: "Puzzles",
    rules:
      "3本の杭があり、最初は1本の杭に全ての円盤が小さい順に積まれています。大きな円盤を小さな円盤の上に置かずに、全ての円盤を別の杭に移動させればクリアです。",
  },
  {
    type: "logic_circuit",
    name: "Logic Circuit Sandbox",
    description: "論理回路を自由に組めるサンドボックスモード。",
    emoji: "🔌",
    minPlayers: 1,
    maxPlayers: 1,
    category: "Special",
    rules:
      "論理ゲートを配置して、自由に回路を組み立てることができます。デジタル回路の仕組みを学んだり、実験したりするのに最適です。",
  },
  {
    type: "logic_lab",
    name: "Logic Lab",
    description: "論理回路パズル。目指せ計算機作り！",
    emoji: "🧠",
    minPlayers: 1,
    maxPlayers: 1,
    category: "Puzzles",
    rules:
      "各レベルの真理値表を満たすように回路を設計します。単純なゲートから始まり、徐々に複雑な回路を目指します。",
  },
];
